const bikeList = [
  {
    name: "rower1",
    color: "Biały",
    price: 270,
    size: "L",
    bounce: "140mm",
    battery: "750wh",
    engine: "Bosch gen 4 Smart",
    img: "/assets/r1.webp",
  },
  {
    name: "rower2",
    color: "Czarny",
    price: 240,
    size: "L",
    bounce: "160mm",
    battery: "625wh",
    engine: "Bosch gen 4 ",
    suspension: "Rock Shox",
    img: "/assets/r2.webp",
  },
  {
    name: "rower3",
    color: "Piaskowy",
    price: 250,
    size: "L",
    bounce: "160mm",
    battery: "750wh",
    engine: "Bosch gen 4 Smart",
    suspension: "Rock Shox",
    img: "/assets/r3.webp",
  },
  {
    name: "rower4",
    color: "PiaskowoCzarny",
    price: 270,
    size: "L",
    bounce: "140mm",
    battery: "625wh",
    engine: "Bosch gen 4 ",
    suspension: "Fox suspension",
    img: "/assets/r4.webp",
  },
];

export default bikeList;
